# Generated by Django 5.2.17 on 2026-09-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_milestone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
